openapi: 3.0.1
info:
  title: Swagger Customer
  description: 'Customer Details'
  termsOfService: http://ey.io/terms/
  contact:
    email: apiteam@ey.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://ey.io
servers:
  - url: https://ey.employee/v1
paths: {}
