apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
    name: external-svc-redirect
spec:
    hosts:
        - "mocky.io"
    location: MESH_EXTERNAL
    ports:
        - number: 443
          name: http
          protocol: HTTP
    resolution: NONE

