apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
    name: tls-routing
spec:
    hosts:
        - mocky.io.org
        - "*.mocky.io.org"
    gateways:
        - generic-gateway
    tls:
        - match:
              - sniHosts:
                    - mocky.io.org
                    - "*.mocky.io.org"
          route:
              - destination:
                    host: internal-egress-firewall.ns1.svc.cluster.local
